services:
  backup:
      image: alpine:latest
      volumes:
        - ./desa_db/dbs:/app/desa_db/dbs:ro # Read-Only access to live DBs
        - ./backups:/app/backups            # Save backups to root/backups
        - ./backup.sh:/backup.sh:ro         # Inject the script
      # Make script executable, set cron to run daily at 02:00 AM, start cron daemon
      command: /bin/sh -c "echo '0 2 * * * /bin/sh /backup.sh' > /etc/crontabs/root && crond -f -d 8"
      restart: always
  backend:
    build: .
    image: integrasi_data_skor_rekomendasi_desa
    command: python desa_db/server.py
    restart: always
    volumes:
      - ./.config:/app/.config
      - ./desa_db/dbs:/app/desa_db/dbs
      - ./desa_db/staging:/app/desa_db/staging
    env_file:
      - .env

  frontend:
    image: integrasi_data_skor_rekomendasi_desa
    command: python front_end/router.py
    restart: always
    environment:
      # Internal Docker URL for SSR Login
      - API_BASE_URL=http://backend:8000 
    volumes:
      - ./.config:/app/.config
    env_file:
      - .env
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80" # This is the SINGLE port you will Tunnel
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
