services:
  backup-integrasi_data_skor_rekomendasi_desa:
      image: alpine:latest
      volumes:
        - ./desa_db/dbs:/app/desa_db/dbs:ro # Read-Only access to live DBs
        - ./backups:/app/backups            # Save backups to root/backups
        - ./backup.sh:/backup.sh:ro         # Inject the script
      # Make script executable, set cron to run daily at 02:00 AM, start cron daemon
      command: /bin/sh -c "/bin/sh /backup.sh && echo '0 2 * * * /bin/sh /backup.sh' > /etc/crontabs/root && crond -f -d 8"
      restart: always

  backend-integrasi_data_skor_rekomendasi_desa:
    build: .
    image: integrasi_data_skor_rekomendasi_desa
    command: python desa_db/server.py
    restart: always
    volumes:
      - ./.config:/app/.config
      - ./desa_db/dbs:/app/desa_db/dbs
      - ./desa_db/temp:/app/desa_db/temp
      - ./exports:/app/exports
      - ./front_end:/app/front_end
    env_file:
      - .env

  frontend-integrasi_data_skor_rekomendasi_desa:
    image: integrasi_data_skor_rekomendasi_desa
    command: python front_end/router.py
    restart: always
    environment:
      # Internal Docker URL for SSR Login
      - API_BASE_URL=http://backend-integrasi_data_skor_rekomendasi_desa:8000 
    volumes:
      - ./.config:/app/.config
      - ./front_end:/app/front_end
    env_file:
      - .env
    depends_on:
      - backend-integrasi_data_skor_rekomendasi_desa

  nginx-integrasi_data_skor_rekomendasi_desa:
    image: nginx:alpine
    ports:
      - "8080:80" # This is the SINGLE port you will Tunnel
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./exports:/app/exports:ro
      - ./front_end/static:/app/front_end/static:ro
    depends_on:
      - backend-integrasi_data_skor_rekomendasi_desa
      - frontend-integrasi_data_skor_rekomendasi_desa
