events {}

http {
  # --- UPLOAD SIZE LIMIT ---
  # Default is 1MB. We increase it to 150MB to allow large chunks/files.
  client_max_body_size 150M;

  server {
    listen 80;
    # on prod if domain exist
    # server_name yourdomain.com www.yourdomain.com;

    # --- TIMEOUT SETTINGS ---
    # Default is 60s. We increase it to 10 minutes.
    proxy_read_timeout 600;
    proxy_connect_timeout 600;
    proxy_send_timeout 600;

    # --- BACKEND ROUTES (Direct to Port 8000) ---
    location ~ ^/(api|config|upload|stage|commit|query|history|download|dashboard|delete) {
        proxy_pass http://backend-integrasi_data_skor_rekomendasi_desa:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # --- FRONTEND ROUTES (Direct to Port 8001) ---
    # Login page, Admin page, Root, Logout
    location / {
        proxy_pass http://frontend-integrasi_data_skor_rekomendasi_desa:8001;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # --- Pre-Compiled Exports ---
    # Serve Pre-Compiled Excel Exports
    location /exports/ {
        alias /app/exports/;
        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;
        # Enable Resumable Downloads (Range Requests)
        add_header Accept-Ranges bytes;
    }
  }
}
